
# rebind prefix
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# vim navigation
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# r for relkad
bind r source ~/.tmux.conf


# colors
# set -g @BG colour235
set -g @FG white
set -g @Bar colour237
set -g @ElementBG colour233
set -g @Active cyan
set -g @Accent purple

# windows

# panes
set -g pane-border-style 'fg=#{@ElementBG}'
set -g pane-active-border-style 'fg=#{@Active}'


# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style ' fg=purple bg=#{@ElementBG}'

set -g status-left ' #[fg=#{@Bar}]<#[fg=#{@Accent}]#S#[fg=#{@Bar}]> #[fg=#{@Bar}]│ '
set -g status-left-length 10

set -g status-right-style 'fg=#{@Accent}'
set -g status-right '#[fg=#{@Bar}]│#[fg=#{@Accent}] %Y-%m-%d #[fg=#{@Bar}]│#[fg=#{@Accent}] %H:%M '
set -g status-right-length 50

# unselected windows
setw -g window-status-style 'fg=#{@Accent} bg=#{@ElementBG}'
setw -g window-status-format '#I:#[fg=white]#W#[fg=#{@Accent}]#F#[fg=#{@Bar}] │'

# selected window
setw -g window-status-current-style 'fg=#{@Active}'
setw -g window-status-current-format '#[bg=#{@Active} fg=black]#I#[bg=#{@ElementBG} fg=#{@Active}]:#W#F#[fg=#{@Bar}] │'

setw -g window-status-bell-style 'fg=yellow bg=red bold'

bind -r % split-window -h -c "#{pane_current_path}"
#bind -r  split-window -v -c "#{pane_current_path}"

set -g message-style 'bg=purple'
